# see: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  # GitHub Actions (/.github/workflows/*.yml)
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '18:00'
      timezone: Asia/Tokyo
    cooldown:
      default-days: 5
    groups:
      actions-artifact:
        patterns:
          - 'actions/download-artifact'
          - 'actions/upload-artifact'
    labels:
      - 'dependabot :robot:'
    commit-message:
      prefix: ci(gh-actions)

  # npm/yarn (/**/package.json)
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: '18:00'
      timezone: Asia/Tokyo
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      oxc: # oxc tools
        dependency-type: development
        patterns:
          - oxlint
          - oxfmt
          - oxlint-tsgolint
      lint-tools: # lint tools (not affected on build)
        dependency-type: development
        patterns:
          - husky
          - lint-staged
          - npm-run-all2
    ignore:
      # Should match the runtime Node.js major version, so keep it manually updated.
      - dependency-name: '@types/node'
        update-types:
          - version-update:semver-major
    labels:
      - 'dependabot :robot:'
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
    open-pull-requests-limit: 10

  # Development Containers (/.devcontainer/devcontainer.json)
  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: daily
      time: '18:00'
      timezone: Asia/Tokyo
    cooldown:
      default-days: 5
    labels:
      - 'dependabot :robot:'
    commit-message:
      prefix: ci(devcontainer)
