name: Node.js CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

permissions:
  actions: read

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-20.04
    steps:
      # Setup Environment
      - uses: actions/checkout@v3.0.2
      - name: Use Node.js 16
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
          cache: npm

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: ESLint
        run: npm run lint:eslint
      - name: Prettier
        run: npm run lint:prettier

  unit-test:
    name: Unit Test
    runs-on: ubuntu-20.04
    steps:
      # Setup Environment
      - uses: actions/checkout@v3.0.2
      - name: Use Node.js 16
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
          cache: npm

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Unit Test
        run: npm test -- --coverage
      - name: Report Code Coverage to codecov
        uses: codecov/codecov-action@v3.1.0

  build-test:
    name: Build & Integration Test
    runs-on: ubuntu-20.04
    steps:
      # Setup Environment
      - uses: actions/checkout@v3.0.2
      - name: Use Node.js 16
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
          cache: npm

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build

      # Integration Test
      - name: Launch this Action
        id: act
        uses: ./
        with:
          contents: |
            foo
            bar
            baz
          weights: |
            10
            10
            10
      - name: Echo Action outputs
        env:
          STEPS_CONTEXT: ${{ toJson(steps.act.outputs) }}
        run: echo $STEPS_CONTEXT
