name: Node.js CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-20.04
    steps:
      # Setup Environment
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js 12
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12

      # Cache
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Dependencies
        uses: actions/cache@v2.1.5
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn --frozen-lockfile --ignore-scripts

      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test --ci
      - name: Report Code Coverage to codecov
        uses: codecov/codecov-action@v1
      - name: GitHub Actions Build Test
        id: act
        uses: ./
        with:
          contents: |
            foo
            bar
            baz
          weights: |
            10
            10
            10
      - name: Echo GitHub Actions outputs
        env:
          STEPS_CONTEXT: ${{ toJson(steps.act.outputs) }}
        run: echo $STEPS_CONTEXT
