name: Node.js CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

permissions:
  actions: read

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-20.04
    steps:
      # Setup Environment
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js 12
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 12
          cache: yarn

      - name: Install Dependencies
        run: yarn --frozen-lockfile --ignore-scripts

      - name: ESLint
        run: yarn lint:eslint
      - name: Prettier
        run: yarn lint:prettier

  unit-test:
    name: Unit Test
    runs-on: ubuntu-20.04
    steps:
      # Setup Environment
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js 12
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 12
          cache: yarn

      - name: Install Dependencies
        run: yarn --frozen-lockfile --ignore-scripts

      - name: Unit Test
        run: yarn test --ci
      - name: Report Code Coverage to codecov
        uses: codecov/codecov-action@v2.1.0

  build-test:
    name: Build & Integration Test
    runs-on: ubuntu-20.04
    steps:
      # Setup Environment
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js 12
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 12
          cache: yarn

      - name: Install Dependencies
        run: yarn --frozen-lockfile --ignore-scripts

      - name: Build
        run: yarn build

      # Integration Test
      - name: Launch this Action
        id: act
        uses: ./
        with:
          contents: |
            foo
            bar
            baz
          weights: |
            10
            10
            10
      - name: Echo Action outputs
        env:
          STEPS_CONTEXT: ${{ toJson(steps.act.outputs) }}
        run: echo $STEPS_CONTEXT
